query($login: String!) {
    user(login: $login) {
        pinnedItems(first: 10, types: REPOSITORY) {
            nodes {
                ... on Repository {
                    nameWithOwner
                }
            }
        }
    }
}
