query($login: String!) {
    user(login: $login) {
        pinnedItems(first: 6, types: REPOSITORY) {
            nodes {
                ... on Repository {
                    nameWithOwner
                    description
                    pushedAt
                    url
                }
            }
        }
    }
}
